### ISSUE TITLE
loading error

### ISSUE THREAD

**Issue by niko-balanis** [FJD-CEPH/aCNViewer#2]
Fyi this error shows up every time I use this program but it does not cause any problems any ideas. The program is still able to output lrr_segment files. Thought you might want ot know about the problem. Any ideas?

Nikolas Balanis

Attaching package: ‘limma’

The following object is masked from ‘package:BiocGenerics’:

plotMA
Error in load("/media/graeberlab/wdblack/CNLOH/raw_data/Top150/") :
restore file may be empty -- no data loaded
In addition: Warning messages:
1: In readChar(con, 5L, useBytes = TRUE) : error reading the file
2: file ‘Top150’ has magic number ''
Use of save versions prior to 2 is deprecated
Execution halted
File "/home/graeberlab/bin/aCNViewer_DATA/bin/ascat/gc" already processed
echo "cel_files" > /media/graeberlab/wdblack/CNLOH/top_output/tmp/list.nsp
ls /media/graeberlab/wdblack/CNLOH/raw_data/Top150/*.cel >> /media/graeberlab/wdblack/CNLOH/top_output/tmp/list.nsp
Step 1.1: Extracting genotypes from CEL files

**Comment by FJD-CEPH** [comment]
Thanks for noticing this message. This error is captured in the script and is the result of the script trying to figure out the input type given. I will remove that message in the next release where small improvements have been added to avoid possible confusions.
